#!/usr/bin/env bash
set -e
yarn run build:prod

rsync \
      --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
      --verbose \
      --archive \
      --update \
      --delete \
      --prune-empty-dirs \
      --copy-links \
      --compress \
      ./dist/ \
      pixelastic:/var/www/www.pixelastic.com/
